### ISSUE TITLE
GitHub releases with version releases

### ISSUE THREAD

**Issue by joshwlambert** [mrc-ide/epireview#107]
It would be nice to do GitHub release when you do major (e.g. v1.0.0 -> v2.0.0) or minor (e.g. v1.1.0 -> v1.2.0) release. (Also patch releases if you want as well but I see that you make quite a lot of patch releases between minor releases so maybe this would be overkill). 

This gives the benefit of allowing comparison of files between versions and allows users to easily install previous versions of the package from GitHub.

**Comment by sangeetabhatia03** [comment]
Thanks for the excellent suggestion, Josh. We will adhere to this practice from here on.
Latest release here https://github.com/mrc-ide/epireview/releases/tag/v1.3.0
