### ISSUE TITLE
Set v1.3.1 as latest to show on {epireview} GitHub homepage

### ISSUE THREAD

**Issue by joshwlambert** [mrc-ide/epireview#121]
The box for the recent v1.3.1 release does not have the set as latest ticked. It is useful to always tick this unless you don't want people to know about the release, in which case it should be written in the release notes why this is not the latest release. Thanks.

**Comment by sangeetabhatia03** [comment]
Thanks @joshwlambert. Suggestion noted, and we will be mindful in the future.
For now, we have updated the latest release to v1.3.1
