### ISSUE TITLE
Fix vignettes

### ISSUE THREAD

**Issue by sangeetabhatia03** [mrc-ide/epireview#22]
Vignettes are broken, they need to be fixed. They are currently sourcing R scripts, this is not necessary.

**Comment by cm401** [comment]
@sangeetabhatia03 lets discuss a potential option for this (which would move the content of the offending vignettes from epireview).

**Comment by sangeetabhatia03** [comment]
This is all sorted out, thanks to @tristan-myles  and @cm401 
Closing now.
