### ISSUE TITLE
functions should print more informative messages

### ISSUE THREAD

**Issue by sangeetabhatia03** [mrc-ide/epireview#27]
e.g. load_epidata should print information about number of studies, number of unique parameters etc.

**Comment by kellymccain28** [comment]
Also, the error message for the forest plot functions when passing the whole list of dataframes exported from load_epidata() (which is incorrect but seems like a common thing people might do) could be more informative - e.g. could prompt the user to pass the parameter data frame.

**Comment by sangeetabhatia03** [comment]
Same as #57 
Closing as duplicate
