### ISSUE TITLE
Improve Warning messages for load_epidata(pathogen)

### ISSUE THREAD

**Issue by cm401** [mrc-ide/epireview#57]
From running the code the following warning for loading Lassa data is generated:

`Data loaded for lassa                                                                                                                     
Warning messages: 1: One or more parsing issues, call problems()on your data frame for details, e.g.: dat <- vroom(...) problems(dat)`

**Comment by sangeetabhatia03** [comment]
My suggestion would be to use {cli}

**Comment by sangeetabhatia03** [comment]
Closed via https://github.com/mrc-ide/epireview/pull/101
