### ISSUE TITLE
accommodating changes in extraction of uncertainty/variability

### ISSUE THREAD

**Issue by annecori** [mrc-ide/epireview#61]
We will need to change the way the pairs of mean/sds are stored in Marburg, Lassa, Ebola and SARS to match the way this is done in Zika - so post processing the current dbs for Marburg etc so the users sees something which looks like ZIka
this will make interfacing with external tools such as epiparameters much easier

**Comment by ruthmccabe** [comment]
and will impact interaction with epiparameter: https://epiverse-trace.github.io/epiparameter/dev/articles/data_from_epireview.html

**Comment by cm401** [comment]
We have a PR to update the vignette. Plan to add Anne's & Anton's Ebola example as a vignette...
[PR](https://github.com/epiverse-trace/epiparameter/pull/305 )

**Comment by kellymccain28** [comment]
Agreed that ideally we would modify the datasets for Ebola, Lassa, SARS, and Marburg to match how it will be extracted from zika onwards to avoid any confusion amongst the users of the database and streamline any analyses
