### ISSUE TITLE
Outcome type column for Marburg data

### ISSUE THREAD

**Issue by CarmenTamayo** [mrc-ide/epireview#65]
Currently the parameters for Marburg include the type of parameter as "Human delay - time symptom to outcome", but as far as I can tell there's no other columns that indicate what type of outcome. It'd be very useful to have this information, for instance the onset-death delay to estimate CFR.

On a related note, to make the database easier to filter and subset, I think it'd also be helpful to split the "parameter type" column into 2, one with "human delay" and the other one with the specific type of delay- at the moment I had to use grepl() to be able to subset by parameter type.

Thanks! @ruthmccabe

**Comment by cm401** [comment]
The particular outcome for this parameter entry was discharge from isolation. In subsequent pathogens we enabled the typing in of what this outcome is, for example for Lassa we have two columns: "other_delay_start" and "other_delay_end" which specifies what these time points are.

**Comment by sangeetabhatia03** [comment]
@cm401 perhaps we should close this issue as we are unlikely to change the data?

**Comment by cm401** [comment]
Yes, Carmen and I had a quick discussion on this a couple of weeks ago. For Marburg for 'outcome other' we used the risk factor outcome column to specify what the other outcome is. 
_For example_:  parameter row 37

I agree that we should close this issue for the time being. This is one example of "backwards compatibility" issues across pathogens. Ideally we come up with a solution for this in the future but Marburg I would leave as is for now.
